import type { Lead, ScanJob } from "@/lib/types";

// Demo records keep Phase 1 usable before Supabase is connected.
export const leads: Lead[] = [
  {
    id: "ruang-bina-studio",
    company: "Ruang Bina Studio",
    niche: "Renovation & interior",
    city: "Shah Alam",
    state: "Selangor",
    score: 88,
    websiteStatus: "Social only",
    opportunity: "Turn recent project posts into a structured portfolio and quotation flow.",
    reason: "Active project updates, a public WhatsApp number and no official website.",
    status: "Draft Ready",
    phone: "+60 12-684 7319",
    whatsapp: "60126847319",
    address: "Seksyen 13, Shah Alam, Selangor",
    social: "https://www.instagram.com/",
    lastSeen: "Today, 8:42 AM",
    discoveredAt: "Today, 8:39 AM",
    englishDraft: "Hi Ruang Bina Studio, I noticed your recent renovation work is shared mainly through social media. A focused portfolio website could help homeowners compare projects and request quotations more easily. I build practical websites for Malaysian businesses and would be happy to share a simple direction for your team.",
    bmDraft: "Hi Ruang Bina Studio, saya perasan projek renovasi terkini banyak dikongsi melalui media sosial. Website portfolio yang kemas boleh bantu pemilik rumah melihat hasil kerja dan meminta sebut harga dengan lebih mudah. Saya membina website praktikal untuk bisnes Malaysia dan boleh kongsikan cadangan ringkas untuk pihak anda.",
    scope: ["Project portfolio", "Quotation enquiry", "Service areas", "WhatsApp handoff"],
    scoreReasons: [
      { label: "No official website", points: 25 },
      { label: "Recent public activity", points: 15 },
      { label: "High-value service niche", points: 15 },
      { label: "WhatsApp available", points: 10 },
      { label: "Active visual branding", points: 10 },
      { label: "Clear portfolio gap", points: 10 },
      { label: "Growth signal", points: 3 },
    ],
  },
  {
    id: "meridian-compliance",
    company: "Meridian Compliance Partners",
    niche: "Corporate services",
    city: "Kuala Lumpur",
    state: "Kuala Lumpur",
    score: 82,
    websiteStatus: "Outdated",
    opportunity: "Clarify specialist services and replace the dated mobile enquiry journey.",
    reason: "Strong review activity and a dated site that is difficult to use on mobile.",
    status: "Qualified",
    phone: "+60 3-2788 4106",
    whatsapp: "60327884106",
    address: "Jalan Tun Razak, Kuala Lumpur",
    website: "https://example.com",
    lastSeen: "Today, 8:41 AM",
    discoveredAt: "Today, 8:35 AM",
    englishDraft: "Hi Meridian Compliance Partners, your specialist services are clearly established, but the current mobile website makes them difficult to compare quickly. I help Malaysian service businesses improve credibility and enquiry flow with focused, responsive websites. May I share a concise homepage direction based on your public service information?",
    bmDraft: "Hi Meridian Compliance Partners, servis kepakaran pihak anda jelas dan kukuh, tetapi website semasa agak sukar digunakan untuk membandingkan servis melalui telefon. Saya membantu bisnes perkhidmatan Malaysia meningkatkan kredibiliti dan aliran pertanyaan melalui website responsif. Boleh saya kongsikan cadangan ringkas untuk halaman utama?",
    scope: ["Corporate profile", "Service pages", "Mobile enquiry", "Trust signals"],
    scoreReasons: [
      { label: "Outdated mobile website", points: 20 },
      { label: "Recent public reviews", points: 15 },
      { label: "High-value service niche", points: 15 },
      { label: "Business phone available", points: 10 },
      { label: "Credibility gap", points: 10 },
      { label: "Clear enquiry gap", points: 10 },
      { label: "Multiple service lines", points: 2 },
    ],
  },
  {
    id: "teluk-senja-stay",
    company: "Teluk Senja Stay",
    niche: "Property & homestay",
    city: "Batu Ferringhi",
    state: "Penang",
    score: 76,
    websiteStatus: "No website",
    opportunity: "Create a direct enquiry page with rooms, availability cues and location details.",
    reason: "Good recent reviews, direct phone contact and no owned booking page.",
    status: "New",
    phone: "+60 11-2085 4472",
    whatsapp: "601120854472",
    address: "Batu Ferringhi, Pulau Pinang",
    social: "https://www.facebook.com/",
    lastSeen: "Today, 8:40 AM",
    discoveredAt: "Today, 8:31 AM",
    englishDraft: "Hi Teluk Senja Stay, I found your accommodation while reviewing stays around Batu Ferringhi. A simple direct enquiry website could gather room details, location information and WhatsApp enquiries in one place without replacing your current channels. I can share a compact example if useful.",
    bmDraft: "Hi Teluk Senja Stay, saya jumpa penginapan pihak anda semasa membuat semakan sekitar Batu Ferringhi. Website pertanyaan terus yang ringkas boleh kumpulkan maklumat bilik, lokasi dan WhatsApp dalam satu tempat tanpa menggantikan saluran sedia ada. Saya boleh kongsikan contoh ringkas jika berminat.",
    scope: ["Room gallery", "Availability enquiry", "Location guide", "Direct WhatsApp"],
    scoreReasons: [
      { label: "No official website", points: 25 },
      { label: "Recent public reviews", points: 15 },
      { label: "Website-relevant niche", points: 15 },
      { label: "WhatsApp available", points: 10 },
      { label: "Direct booking gap", points: 10 },
      { label: "Active social presence", points: 1 },
    ],
  },
  {
    id: "northline-auto-detailing",
    company: "Northline Auto Detailing",
    niche: "Automotive",
    city: "Skudai",
    state: "Johor",
    score: 64,
    websiteStatus: "Social only",
    opportunity: "Present packages and make service enquiries easier to qualify.",
    reason: "Clear service packages on social media but no owned comparison page.",
    status: "New",
    phone: "+60 16-441 9098",
    whatsapp: "60164419098",
    address: "Taman Universiti, Skudai, Johor",
    social: "https://www.facebook.com/",
    lastSeen: "Yesterday, 5:18 PM",
    discoveredAt: "Yesterday, 5:13 PM",
    englishDraft: "Hi Northline Auto Detailing, your service packages are visible on social media, but customers may need to scroll to compare them. A compact service website could make package selection and WhatsApp enquiries faster. I build practical websites for Malaysian businesses and can share a simple direction.",
    bmDraft: "Hi Northline Auto Detailing, pakej servis pihak anda ada di media sosial, tetapi pelanggan perlu banyak scroll untuk membandingkannya. Website servis yang ringkas boleh mudahkan pemilihan pakej dan pertanyaan WhatsApp. Saya membina website praktikal untuk bisnes Malaysia dan boleh kongsikan cadangan ringkas.",
    scope: ["Package comparison", "Before and after gallery", "Booking enquiry"],
    scoreReasons: [
      { label: "Social-only presence", points: 20 },
      { label: "Business phone available", points: 10 },
      { label: "Active social branding", points: 10 },
      { label: "Service comparison gap", points: 10 },
      { label: "Recent reviews", points: 9 },
    ],
  },
];

export const scans: ScanJob[] = [
  { id: "scan-2026-09-03-0830", status: "completed_with_leads", startedAt: "Today, 8:30 AM", completedAt: "Today, 8:44 AM", niche: "Corporate services", cities: ["Kuala Lumpur", "Shah Alam"], scanned: 47, newLeads: 5, qualified: 3, notifications: 3 },
  { id: "scan-2026-09-03-0530", status: "completed_no_leads", startedAt: "Today, 5:30 AM", completedAt: "Today, 5:39 AM", niche: "Cafes & restaurants", cities: ["George Town", "Bukit Mertajam"], scanned: 31, newLeads: 1, qualified: 0, notifications: 0 },
  { id: "scan-2026-09-03-0230", status: "failed", startedAt: "Today, 2:30 AM", completedAt: "Today, 2:32 AM", niche: "Automotive", cities: ["Johor Bahru", "Skudai"], scanned: 0, newLeads: 0, qualified: 0, notifications: 0, error: "Places quota guard stopped the job before any request was sent." },
];

export const commandCentre = {
  status: "idle" as const,
  nextScan: "1h 42m",
  lastScan: "1h 18m ago",
  today: { newLeads: 5, highPriority: 2, waiting: 3, contacted: 1, replied: 0, wonLost: 0 },
};
